# 模块跟目录
path: modules

# 配置主题
theme: 大技术平台

# 输出文件
# .min.js 代表输出压缩后的js文件
out:
  - dist/ui.css

# 模块列表
modules:
  - reset
  - tool
  - margin
  - column
  - text
  - link
  - button
  - input
  - table
  # - list
  - tab
  - label
  - tip
  # - notice
  # - page
  # - popup
  - progress
  # - calendar
  # - form
  # - textarea
  # - step
  # - banner
  # - checkboxradio
  # - banner
  - demo
